---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflows__mount_and_unmount_datastores.html 
keywords:  
summary: Um Mount- und Unmount-Vorgänge für Datenspeichersicherungen mithilfe des SnapCenter Plug-in for VMware vSphere REST-APIs durchzuführen, müssen Sie die vorgeschriebene Reihenfolge der REST-API-Aufrufe einhalten. 
---
= REST-API-Workflows zum Mounten und Unmounten von Datenspeichern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Um Mount- und Unmount-Vorgänge für Datenspeichersicherungen mithilfe des SnapCenter Plug-in for VMware vSphere REST-APIs durchzuführen, müssen Sie die vorgeschriebene Reihenfolge der REST-API-Aufrufe einhalten.

Fügen Sie für jede REST-API hinzu `\https://<server>:<port>` an der Vorderseite der REST-API, um einen vollständigen Endpunkt zu bilden.



== Um Datenspeicher zu mounten, folgen Sie diesem Workflow:

|===
| Schritt | REST-API | Kommentare 


| 1 | Gehe zu `\http://<vCenter-IP>/mob` | Suchen Sie den Datenspeicher moref über die VMware Managed Objects-URL.  Notieren Sie sich das *moref* für den Datenspeicher, den Sie mounten möchten. 


| 2 | `/4.1/datastores/{moref}/
backups` | `Get the list of backups for a datastore`Ruft eine Liste der Sicherungen für den angegebenen Datenspeicher ab.  Übergeben Sie das *moref* aus Schritt 1.  Notieren Sie sich die *Backup-ID*, die Sie mounten möchten. 


| 3 | `/4.1/datastores/backups/
{backupId}/snapshotlocators` | `Get the list of Snapshot Locations`Ruft Details zum Speicherort der angegebenen Sicherung ab.  Übergeben Sie die *Backup-ID* aus Schritt 2.  Notieren Sie sich den *Datenspeicher* und den Speicherort aus der Liste *snapshotLocationsList*. 


| 4 | `/4.1/datastores/{moref}/
availableEsxHosts` | `Get the list of Available Esxi Hosts`Ruft die Liste der ESXi-Hosts ab, die für Mountvorgänge verfügbar sind.  Übergeben Sie das *moref* aus Schritt 1.  Beachten Sie die Informationen *availableEsxHostsList*. 


| 5 | `/4.1/datastores/backups/
{backupId}/mount` | `Mount datastores for a backup`mountet die angegebene Datenspeichersicherung.  Übergeben Sie die *Backup-ID* aus Schritt 2.  Übergeben Sie in den Attributen *datastore* und *location* die Informationen von `snapshotLocationsList` in Schritt 3.  Übergeben Sie im Attribut *esxHostName* die Informationen aus *availableEsxHostsList* in Schritt 4. 
|===


== Um die Bereitstellung von Datenspeichern aufzuheben, folgen Sie diesem Arbeitsablauf:

|===
| Schritt | REST-API | Kommentare 


| 1 | `/4.1/datastores/backups/
{backupId}/mounted` | `Get the list of mounted datastores` . Notieren Sie sich die *moref*-Datenspeicher, die Sie aushängen möchten. 


| 2 | `/4.1/datastores/unmount` | `UnMount datastores for a backup`hebt die Bereitstellung der angegebenen Datenspeichersicherung auf.  Übergeben Sie den/die Datenspeicher *moref* aus Schritt 1. 
|===