---
sidebar: sidebar 
permalink: scpivs44_manage_storage_systems.html 
keywords:  
summary: Bevor Sie VMs oder Datenspeicher mit dem VMware vSphere-Client sichern oder wiederherstellen können, müssen Sie den Speicher hinzufügen. 
---
= Speichersysteme verwalten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bevor Sie VMs oder Datenspeicher mit dem VMware vSphere-Client sichern oder wiederherstellen können, müssen Sie den Speicher hinzufügen.



== Ändern von Speicher-VMs

Sie können den VMware vSphere-Client verwenden, um die Konfigurationen von Clustern und Speicher-VMs zu ändern, die im SnapCenter Plug-in for VMware vSphere registriert sind und für VM-Datenschutzvorgänge verwendet werden.

Wenn Sie eine Speicher-VM ändern, die automatisch als Teil eines Clusters hinzugefügt wurde (manchmal auch als implizite Speicher-VM bezeichnet), wird diese Speicher-VM zu einer expliziten Speicher-VM und kann separat gelöscht werden, ohne dass die restlichen Speicher-VMs in diesem Cluster geändert werden.  Auf der Seite „Speichersysteme“ wird der Benutzername als N/A angezeigt, wenn die Authentifizierungsmethode über das Zertifikat erfolgt. Benutzernamen werden nur für explizite Speicher-VMs in der Clusterliste angezeigt und haben das Flag „ExplicitSVM“ auf „true“ gesetzt.  Alle Storage-VMs werden immer unter dem zugehörigen Cluster aufgelistet.


IMPORTANT: Wenn Sie Speicher-VMs für anwendungsbasierte Datenschutzvorgänge mithilfe der SnapCenter -GUI hinzugefügt haben, müssen Sie dieselbe GUI verwenden, um diese Speicher-VMs zu ändern.

.Schritte
. Wählen Sie im linken Navigationsbereich des SCV-Plug-Ins *Speichersysteme* aus.
. Wählen Sie auf der Seite *Speichersysteme* die zu ändernde Speicher-VM aus und wählen Sie dann *Bearbeiten*.
. Geben Sie im Fenster *Speichersystem bearbeiten* die neuen Werte ein und wählen Sie dann *Aktualisieren*, um die Änderungen anzuwenden.




== Entfernen von Speicher-VMs

Sie können den VMware vSphere-Client verwenden, um Speicher-VMs aus dem Inventar in vCenter zu entfernen.


NOTE: Wenn Sie Speicher-VMs für anwendungsbasierte Datenschutzvorgänge mithilfe der SnapCenter -GUI hinzugefügt haben, müssen Sie dieselbe GUI verwenden, um diese Speicher-VMs zu ändern.

.Bevor Sie beginnen
Sie müssen alle Datenspeicher in der Speicher-VM aushängen, bevor Sie die Speicher-VM entfernen können.

.Informationen zu diesem Vorgang
Wenn eine Ressourcengruppe über Sicherungen verfügt, die sich auf einer Speicher-VM befinden, die Sie entfernen, schlagen nachfolgende Sicherungen für diese Ressourcengruppe fehl.

.Schritte
. Wählen Sie im linken Navigationsbereich des SCV-Plug-Ins *Speichersysteme* aus.
. Wählen Sie auf der Seite *Speichersysteme* die zu entfernende Speicher-VM aus und wählen Sie dann *Löschen*.
. Aktivieren Sie im Bestätigungsfeld *Speichersystem entfernen* das Kontrollkästchen *Speichersystem(e) löschen* und wählen Sie dann zur Bestätigung *Ja*.  *Hinweis:* Es werden nur ESXi-Host 7.0U1 und spätere Versionen unterstützt.
+
link:scpivs44_restart_the_vmware_vsphere_web_client_service.html["Starten Sie den VMware vSphere-Clientdienst neu"] .


