---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere_01.html 
keywords:  
summary:  
---
= Bereitstellen des SnapCenter Plug-in for VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Um SnapCenter -Funktionen zum Schutz von VMs, Datenspeichern und anwendungskonsistenten Datenbanken auf virtualisierten Maschinen zu verwenden, müssen Sie das SnapCenter Plug-in for VMware vSphere bereitstellen.  Derlink:scpivs44_download_the_ova_open_virtual_appliance.html["Laden Sie die Open Virtual Appliance (OVA) herunter"^] Seite enthält Anweisungen zum Herunterladen der OVA-Dateien.

. Für VMware vCenter 7.0.3 und spätere Versionen folgen Sie den Schritten inlink:scpivs44_download_the_ova_open_virtual_appliance.html["Laden Sie die Open Virtual Appliance (OVA) herunter"^] um die Zertifikate in vCenter zu importieren.
. Navigieren Sie in Ihrem Browser zu VMware vSphere vCenter.
+

NOTE: Für HTML-Webclients mit IPv6-Adressen müssen Sie entweder Chrome oder Firefox verwenden.

. Melden Sie sich auf der *VMware vCenter Single Sign-On-Seite* an.
. Klicken Sie im Navigationsbereich mit der rechten Maustaste auf ein beliebiges Bestandsobjekt, das ein gültiges übergeordnetes Objekt einer virtuellen Maschine ist, z. B. ein Rechenzentrum, Ordner, Cluster oder Host, und wählen Sie *OVF-Vorlage bereitstellen* aus, um den VMware-Bereitstellungsassistenten zu starten.
. Geben Sie auf der Seite *Wählen Sie eine OVF-Vorlage* den Speicherort der `.ova` Datei (wie in der folgenden Tabelle aufgeführt) und wählen Sie *Weiter*.
+
|===
| Auf dieser Assistentenseite … | Mach das… 


| Wählen Sie einen Namen und einen Ordner | Geben Sie einen eindeutigen Namen für die VM oder vApp ein und wählen Sie einen Bereitstellungsort aus. 


| Wählen Sie eine Ressource aus | Wählen Sie eine Ressource aus, auf der Sie die bereitgestellte VM-Vorlage ausführen möchten. 


| Bewertungsdetails | Überprüfen Sie die `.ova` Vorlagendetails. 


| Lizenzvereinbarungen | Aktivieren Sie das Kontrollkästchen *Ich akzeptiere alle Lizenzvereinbarungen*. 


| Speicher auswählen | Definieren Sie, wo und wie die Dateien für die bereitgestellte OVF-Vorlage gespeichert werden sollen. 


| Netzwerke auswählen | Wählen Sie ein Quellnetzwerk aus und ordnen Sie es einem Zielnetzwerk zu. 


| Vorlage anpassen  a| 
Geben Sie unter *Bei vorhandenem vCenter registrieren* die vCenter-Anmeldeinformationen ein.  Geben Sie unter *Anmeldeinformationen für SnapCenter Plug-in for VMware vSphere erstellen* die Anmeldeinformationen für SnapCenter Plug-in for VMware vSphere ein.


NOTE: Notieren Sie sich den Benutzernamen und das Passwort, die Sie angeben.  Sie müssen diese Anmeldeinformationen verwenden, wenn Sie die Konfiguration des SnapCenter -Plug-Ins für VMware vSphere zu einem späteren Zeitpunkt ändern möchten.

Geben Sie im Abschnitt *Netzwerkeigenschaften einrichten* die Netzwerkinformationen ein.  Wählen Sie im Abschnitt *Datum und Uhrzeit einrichten* die Zeitzone aus, in der sich das vCenter befindet.



| Bereit zum Abschließen | Überprüfen Sie die Seite und wählen Sie *Fertig*. 
|===
+

NOTE: Alle Hosts müssen mit IP-Adressen konfiguriert werden (FQDN-Hostnamen werden nicht unterstützt).  Der Bereitstellungsvorgang validiert Ihre Eingabe vor der Bereitstellung nicht.

. Navigieren Sie zu der VM, auf der das SnapCenter Plug-in for VMware vSphere bereitgestellt wurde, wählen Sie dann die Registerkarte *Zusammenfassung* und anschließend das Feld *Einschalten* aus, um das SnapCenter Plug-in for VMware vSphere zu starten.
. Klicken Sie beim Einschalten des SnapCenter Plug-in for VMware vSphere mit der rechten Maustaste auf das bereitgestellte SnapCenter Plug-in for VMware vSphere, wählen Sie *Gastbetriebssystem* und dann *VMware-Tools installieren*.
+
Die Bereitstellung kann einige Minuten dauern.  Eine erfolgreiche Bereitstellung wird angezeigt, wenn das SnapCenter Plug-in for VMware vSphere eingeschaltet ist, die VMware-Tools installiert sind und Sie auf dem Bildschirm aufgefordert werden, sich beim SnapCenter Plug-in for VMware vSphere anzumelden.

+
Auf dem Bildschirm wird die IP-Adresse angezeigt, unter der das SnapCenter Plug-in for VMware vSphere bereitgestellt wird. Notieren Sie sich die IP-Adresse. Sie müssen sich bei der Verwaltungs-GUI des SnapCenter Plug-in for VMware vSphere anmelden, wenn Sie Änderungen an der Konfiguration des SnapCenter Plug-in for VMware vSphere vornehmen möchten.

. Melden Sie sich mit der auf dem Bereitstellungsbildschirm angezeigten IP-Adresse und den Anmeldeinformationen, die Sie im Bereitstellungsassistenten angegeben haben, bei der Verwaltungs-GUI des SnapCenter Plug-in for VMware vSphere für SnapCenter Plug-in for VMware vSphere erfolgreich mit vCenter verbunden und aktiviert ist.
+
Verwenden Sie das Format `\https://<appliance-IP-address>:8080` um auf die Verwaltungs-GUI zuzugreifen.

+
Melden Sie sich mit dem zum Zeitpunkt der Bereitstellung festgelegten Administratorbenutzernamen und -kennwort sowie dem mithilfe der Wartungskonsole generierten MFA-Token an.

. Melden Sie sich beim vCenter HTML5-Client an, wählen Sie dann *Menü* in der Symbolleiste und dann * SnapCenter Plug-in for VMware vSphere*

