---
sidebar: sidebar 
permalink: scpivs44_disable_and_enable_plugin.html 
keywords:  
summary: Wenn Sie die Datenschutzfunktionen von SnapCenter nicht mehr benötigen, müssen Sie die Konfiguration des SnapCenter Plug-in for VMware vSphere ändern.  Wenn Sie das Plug-In beispielsweise in einer Testumgebung bereitgestellt haben, müssen Sie möglicherweise die SnapCenter -Funktionen in dieser Umgebung deaktivieren und in einer Produktionsumgebung aktivieren. 
---
= Deaktivieren und Aktivieren des SnapCenter Plug-in for VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie die Datenschutzfunktionen von SnapCenter nicht mehr benötigen, müssen Sie die Konfiguration des SnapCenter Plug-in for VMware vSphere ändern.  Wenn Sie das Plug-In beispielsweise in einer Testumgebung bereitgestellt haben, müssen Sie möglicherweise die SnapCenter -Funktionen in dieser Umgebung deaktivieren und in einer Produktionsumgebung aktivieren.

.Bevor Sie beginnen
* Sie müssen über Administratorrechte verfügen.
* Stellen Sie sicher, dass keine SnapCenter -Jobs ausgeführt werden.


.Informationen zu diesem Vorgang
Wenn Sie das SnapCenter Plug-in for VMware vSphere deaktivieren, werden alle Ressourcengruppen angehalten und die Registrierung des Plug-ins als Erweiterung in vCenter aufgehoben.

Wenn Sie das SnapCenter Plug-in for VMware vSphere aktivieren, wird das Plug-in als Erweiterung in vCenter registriert, alle Ressourcengruppen befinden sich im Produktionsmodus und alle Zeitpläne sind aktiviert.

.Schritte
. Optional: Sichern Sie das SnapCenter Plug-in for VMware vSphere MySQL-Repository, falls Sie es auf einer neuen virtuellen Appliance wiederherstellen möchten.
+
link:scpivs44_back_up_the_snapcenter_plug-in_for_vmware_vsphere_mysql_database.html["Sichern Sie das SnapCenter Plug-in for VMware vSphere MySQL-Datenbank"] .

. Melden Sie sich beim SnapCenter Plug-in for VMware vSphere Management GUI mit dem Format `\https://<OVA-IP-address>:8080` . Melden Sie sich mit dem zum Zeitpunkt der Bereitstellung festgelegten Administratorbenutzernamen und -kennwort sowie dem mithilfe der Wartungskonsole generierten MFA-Token an.
+
Die IP-Adresse des SnapCenter Plug-in for VMware vSphere wird angezeigt, wenn Sie das Plug-in bereitstellen.

. Wählen Sie im linken Navigationsbereich *Konfiguration* aus und deaktivieren Sie dann die Option „Dienst“ im Abschnitt *Plug-in-Details*, um das Plug-in zu deaktivieren.
. Bestätigen Sie Ihre Auswahl.
+
** Wenn Sie nur das SnapCenter Plug-in for VMware vSphere verwendet haben, um VM-konsistente Backups durchzuführen
+
Das Plug-In ist deaktiviert und es sind keine weiteren Maßnahmen erforderlich.

** Wenn Sie das SnapCenter Plug-in for VMware vSphere verwendet haben, um anwendungskonsistente Backups durchzuführen
+
Das Plug-In ist deaktiviert und eine weitere Bereinigung ist erforderlich.

+
... Melden Sie sich bei VMware vSphere an.
... Schalten Sie die VM aus.
... Klicken Sie im linken Navigator-Bildschirm mit der rechten Maustaste auf die Instanz des SnapCenter Plug-in for VMware vSphere (der Name des `.ova` Datei, die bei der Bereitstellung der virtuellen Appliance verwendet wurde) und wählen Sie *Von Festplatte löschen*.
... Melden Sie sich bei SnapCenter an und entfernen Sie den vSphere-Host.





