---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflows__modify_built-in_schedules.html 
keywords:  
summary: Um integrierte Zeitpläne für VMware vSphere-Clientjobs mithilfe des SnapCenter Plug-in for VMware vSphere REST-APIs zu ändern, müssen Sie die vorgeschriebene Reihenfolge der REST-API-Aufrufe einhalten. 
---
= REST-API-Workflow zum Ändern integrierter Zeitpläne
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Um integrierte Zeitpläne für VMware vSphere-Clientjobs mithilfe des SnapCenter Plug-in for VMware vSphere REST-APIs zu ändern, müssen Sie die vorgeschriebene Reihenfolge der REST-API-Aufrufe einhalten.

Integrierte Zeitpläne sind die Zeitpläne, die als Teil des Produkts bereitgestellt werden, beispielsweise der Zeitplan für den MySQL-Datenbank-Dump.  Sie können die folgenden Zeitpläne ändern:
`Schedule-DatabaseDump`
`Schedule-PurgeBackups`
`Schedule-AsupDataCollection`
`Schedule-ComputeStorageSaving`
`Schedule-PurgeJobs`

Fügen Sie für jede REST-API hinzu `\https://<server>:<port>` an der Vorderseite der REST-API, um einen vollständigen Endpunkt zu bilden.

|===
| Schritt | REST-API | Kommentare 


| 1 | `/4.1/schedules` | `Get all built-in`schedules ruft eine Liste der Jobpläne ab, die ursprünglich im Produkt bereitgestellt wurden.  Notieren Sie den Zeitplannamen, den Sie ändern möchten, und den zugehörigen Cron-Ausdruck. 


| 2 | `/4.1/schedules` | `Modify any built-in schedule`ändert den benannten Zeitplan.  Übergeben Sie den Zeitplannamen aus Schritt 1 und erstellen Sie einen neuen Cron-Ausdruck für den Zeitplan. 
|===