---
sidebar: sidebar 
permalink: scpivs44_unregister_plugin_from_vcenter.html 
keywords:  
summary: Wenn Sie den Dienst „SnapCenter Plug-in for VMware vSphere“ in einem vCenter im verknüpften Modus beenden, sind Ressourcengruppen nicht in allen verknüpften vCentern verfügbar, selbst wenn der Dienst „SnapCenter Plug-in for VMware vSphere“ in den anderen verknüpften vCentern ausgeführt wird.  Sie müssen die Registrierung des SnapCenter Plug-in for VMware vSphere Erweiterungen manuell aufheben. 
---
= Aufheben der Registrierung des SnapCenter Plug-in for VMware vSphere bei vCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie den Dienst „SnapCenter Plug-in for VMware vSphere“ in einem vCenter im verknüpften Modus beenden, sind Ressourcengruppen nicht in allen verknüpften vCentern verfügbar, selbst wenn der Dienst „SnapCenter Plug-in for VMware vSphere“ in den anderen verknüpften vCentern ausgeführt wird.

Sie müssen die Registrierung des SnapCenter Plug-in for VMware vSphere Erweiterungen manuell aufheben.

.Schritte
. Navigieren Sie im verknüpften vCenter, bei dem der Dienst SnapCenter Plug-in for VMware vSphere gestoppt ist, zum Managed Object Reference (MOB)-Manager.
. Wählen Sie in der Option „Eigenschaften“ in der Spalte „Wert“ die Option „*Inhalt*“ aus und wählen Sie dann im nächsten Bildschirm in der Spalte „Wert“ die Option „*ExtensionManager*“, um eine Liste der registrierten Erweiterungen anzuzeigen.
. Aufheben der Registrierung der Erweiterungen `com.netapp.scv.client` Und `com.netapp.aegis` .

