---
sidebar: sidebar 
permalink: scpivs44_configure_credentials_for_vm_guest_file_restores.html 
keywords:  
summary: Wenn Sie eine virtuelle Festplatte für Datei- oder Ordnerwiederherstellungsvorgänge eines Gastes anhängen, müssen vor der Wiederherstellung die Anmeldeinformationen der Ziel-VM für den Anschluss konfiguriert sein. 
---
= Konfigurieren Sie Anmeldeinformationen für die Wiederherstellung von VM-Gastdateien
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie eine virtuelle Festplatte für Datei- oder Ordnerwiederherstellungsvorgänge eines Gastes anhängen, müssen vor der Wiederherstellung die Anmeldeinformationen der Ziel-VM für den Anschluss konfiguriert sein.

.Informationen zu diesem Vorgang
In der folgenden Tabelle sind die Anmeldeinformationsanforderungen für Gastwiederherstellungsvorgänge aufgeführt.

|===
|  | Benutzerzugriffskontrolle aktiviert | Benutzerzugriffskontrolle deaktiviert 


| Domänenbenutzer | Ein Domänenbenutzer mit dem Benutzernamen „Administrator“ funktioniert einwandfrei.  Beispiel: „NetApp\administrator“.  Ein Domänenbenutzer mit dem Benutzernamen „xyz“, der zu einer lokalen Administratorgruppe gehört, funktioniert jedoch nicht.  Beispielsweise können Sie „NetApp\xyz“ nicht verwenden. | Entweder ein Domänenbenutzer mit dem Benutzernamen „Administrator“ oder ein Domänenbenutzer mit dem Benutzernamen „xyz“, der zu einer lokalen Administratorgruppe gehört, funktioniert einwandfrei.  Beispiel: „NetApp\administrator“ oder „NetApp\xyz“. 


| Arbeitsgruppenbenutzer | Ein lokaler Benutzer mit dem Benutzernamen „Administrator“ funktioniert einwandfrei.  Ein lokaler Benutzer mit dem Benutzernamen „xyz“, der zu einer lokalen Administratorgruppe gehört, funktioniert jedoch nicht. | Entweder ein lokaler Benutzer mit dem Benutzernamen „Administrator“ oder ein lokaler Benutzer mit dem Benutzernamen „xyz“, der zu einer lokalen Administratorgruppe gehört, funktioniert einwandfrei.  Ein lokaler Benutzer mit dem Benutzernamen „xyz“, der nicht zur lokalen Administratorgruppe gehört, funktioniert jedoch nicht. 
|===
In den vorhergehenden Beispielen ist „NetApp“ der Dummy-Domänenname und „xyz“ der Dummy-lokale Benutzername

.Schritte
. Wählen Sie im Verknüpfungsfenster des vSphere-Clients unter Plug-Ins * SnapCenter Plug-in for VMware vSphere* aus.
. Wählen Sie in der linken Navigation *Guest File Restore* aus.
. Führen Sie im Abschnitt „Anmeldeinformationen für „Ausführen als““ einen der folgenden Schritte aus:
+
|===
| Um dies zu tun… | Mach das… 


| Vorhandene Anmeldeinformationen verwenden | Wählen Sie eine der konfigurierten Anmeldeinformationen aus. 


| Neue Anmeldeinformationen hinzufügen  a| 
.. Wählen Sie *Hinzufügen*.
.. Geben Sie im Dialogfeld *Anmeldeinformationen für „Ausführen als“* die Anmeldeinformationen ein.  Als Benutzernamen müssen Sie „Administrator“ eingeben.
.. Wählen Sie *VM auswählen* und wählen Sie dann im Dialogfeld *Proxy-VM* eine VM aus.  Wählen Sie *Speichern*, um zum Dialogfeld *Anmeldeinformationen für „Ausführen als“* zurückzukehren.  Wählen Sie die VM aus, die zur Authentifizierung der Anmeldeinformationen verwendet werden soll.


|===
+
Das SnapCenter Plug-in for VMware vSphere verwendet die ausgewählten Anmeldeinformationen, um sich bei der ausgewählten VM anzumelden.

. Wählen Sie *Speichern*.

