---
sidebar: sidebar 
permalink: scpivs44_download_the_snapcenter_plug-in_for_vmware_vsphere_ova_open_virtual_appliance.html 
keywords:  
summary: Sie können die TAR-Datei für das SnapCenter Plug-in for VMware vSphere von der NetApp -Support-Site herunterladen. 
---
= Laden Sie die Open Virtual Appliance (OVA) herunter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Fügen Sie vor der Installation der Open Virtual Appliance (OVA) das Zertifikat zum vCenter hinzu.  Die TAR-Datei enthält die OVA- und Entrust-Stamm- und Zwischenzertifikate. Die Zertifikate befinden sich im Zertifikatsordner.  Die OVA-Bereitstellung wird in VMware vCenter 7u1 und höher unterstützt.

In VMware vCenter-Versionen ab 7.0.3 wird der mit dem Entrust-Zertifikat signierten OVA nicht mehr vertraut.  Sie müssen das folgende Verfahren durchführen, um das Problem zu beheben.

.Schritte
. So laden Sie das SnapCenter -Plug-in für VMware herunter:
+
** Melden Sie sich bei der NetApp Support Site an ( https://mysupport.netapp.com/products/index.html["https://mysupport.netapp.com/products/index.html"^] ).
** Wählen Sie aus der Produktliste * SnapCenter Plug-in for VMware vSphere* und dann die Schaltfläche *Neueste Version herunterladen*.
** Laden Sie das SnapCenter Plug-in for VMware vSphere herunter `.tar` Datei an einen beliebigen Ort.


. Melden Sie sich mit dem vSphere-Client beim vCenter Server an.
. Navigieren Sie zu *Administration > Zertifikate > Zertifikatsverwaltung*.
. Wählen Sie neben *Trusted Root Store* die Option *Hinzufügen*
. Durchsuchen Sie den Speicherort der Entrust-Stamm- und Zwischenzertifikate und wählen Sie ihn aus.  Das Zertifikat wird in einem Panel unter *Vertrauenswürdige Stammzertifikate* hinzugefügt. Sobald die Zertifikate installiert sind, kann OVA überprüft und bereitgestellt werden.



NOTE: Wenn die heruntergeladene OVA-Datei nicht manipuliert wurde, wird in der Spalte *Herausgeber* *Vertrauenswürdiges Zertifikat* angezeigt.
