---
sidebar: sidebar 
permalink: scpivs44_unmount_a_backup.html 
keywords:  
summary: Sie können die Bereitstellung einer Sicherung aufheben, wenn Sie nicht mehr auf die Dateien im Datenspeicher zugreifen müssen. 
---
= Ein Backup aushängen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Bereitstellung einer Sicherung aufheben, wenn Sie nicht mehr auf die Dateien im Datenspeicher zugreifen müssen.

Wenn ein Backup in der VMware vSphere-Client-GUI als gemountet aufgeführt ist, aber nicht im Bildschirm zum Unmounten von Backups aufgeführt ist, müssen Sie die REST-API verwenden `/backup/{backup-Id}/cleanup` um die Out-of-Bound-Datenspeicher zu bereinigen und dann den Unmount-Vorgang erneut zu versuchen.

Wenn Sie versuchen, eine Sicherungskopie eines NFS-Datenspeichers auf einer Speicher-VM (SVM) mit dem Stammvolume in einer Lastenteilungs-Spiegelbeziehung zu mounten, tritt möglicherweise der Fehler `You may have reached the maximum number of NFS volumes configured in the vCenter. Check the vSphere Client for any error messages.` Um dieses Problem zu vermeiden, ändern Sie die Einstellung für die maximalen Volumes, indem Sie zu *ESX* > *Verwalten* > *Einstellungen* > *Erweiterte Systemeinstellungen* navigieren und den Wert NFS.MaxVolumes ändern. Der Maximalwert ist 256.

.Schritte
. Wählen Sie auf der Verknüpfungsseite des VMware vSphere-Clients *Speicher* aus.
. Klicken Sie im linken Navigationsbereich mit der rechten Maustaste auf einen Datenspeicher, wählen Sie dann in der Dropdownliste „SnapCenter Plug-in for VMware vSphere“ und anschließend in der sekundären Dropdownliste „Unmounten“ aus.
+

IMPORTANT: Stellen Sie sicher, dass Sie den richtigen Datenspeicher zum Unmounten auswählen.  Andernfalls kann es zu Beeinträchtigungen der Produktionsarbeit kommen.

. Wählen Sie im Dialogfeld *Unmount Cloned Datastore* einen Datenspeicher aus, aktivieren Sie das Kontrollkästchen *Unmount the cloned datastore* und wählen Sie dann *Unmount*.

