---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflows__create_and_modify_resource_groups.html 
keywords:  
summary: Um Vorgänge zum Erstellen und Ändern von Ressourcengruppen mithilfe des SnapCenter Plug-in for VMware vSphere REST-APIs durchzuführen, müssen Sie die vorgeschriebene Reihenfolge der REST-API-Aufrufe einhalten. 
---
= REST-API-Workflows zum Erstellen und Ändern von Ressourcengruppen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Um Vorgänge zum Erstellen und Ändern von Ressourcengruppen mithilfe des SnapCenter Plug-in for VMware vSphere REST-APIs durchzuführen, müssen Sie die vorgeschriebene Reihenfolge der REST-API-Aufrufe einhalten.

Fügen Sie für jede REST-API hinzu `\https://<server>:<port>` an der Vorderseite der REST-API, um einen vollständigen Endpunkt zu bilden.

Um Ressourcengruppen zu erstellen, folgen Sie diesem Workflow:

|===
| Schritt | REST-API | Kommentare 


| 1 | `/4.1/policies` | `Get Policies`Ruft die Liste der VMware vSphere-Clientrichtlinien ab.  Notieren Sie sich die *policyId*, die Sie beim Erstellen der Ressourcengruppe und der Richtlinien-*Häufigkeit* verwenden möchten.  Wenn keine Richtlinien aufgelistet sind, verwenden Sie die `Create Policy` REST-API zum Erstellen einer neuen Richtlinie. 


| 2 | `/4.1/resource-groups` | `Create a Resource Group`erstellt eine Ressourcengruppe mit der angegebenen Richtlinie.  Übergeben Sie die *policyId* aus Schritt 1 und geben Sie zusätzlich zu allen anderen erforderlichen Attributen die Details zur *Häufigkeit* der Richtlinie ein.  Sie können den sekundären Schutz mithilfe dieser REST-API aktivieren. 
|===
Um Ressourcengruppen zu ändern, folgen Sie diesem Workflow:

|===
| Schritt | REST-API | Kommentare 


| 1 | `/4.1/resource-groups` | `Get List of Resource Groups`Ruft die Liste der VMware vSphere-Client-Ressourcengruppen ab.  Notieren Sie sich die *resourceGroupId*, die Sie ändern möchten. 


| 2 | `/4.1/policies` | Wenn Sie die zugewiesenen Richtlinien ändern möchten, `Get Policies` Ruft die Liste der VMware vSphere-Clientrichtlinien ab.  Notieren Sie sich die *policyId*, die Sie beim Ändern der Ressourcengruppe und der Richtlinien-*Häufigkeit* verwenden möchten. 


| 3 | `/4.1/resource-groups/
{resouceGroupId}` | `Update a Resource Group`ändert die angegebene Ressourcengruppe.  Übergeben Sie die *resourceGroupId* aus Schritt 1.  Übergeben Sie optional die *policyId* aus Schritt 2 und geben Sie zusätzlich zu allen anderen erforderlichen Attributen die *frequency*-Details ein. 
|===