---
permalink: scv_rn_upgrade_paths.html 
sidebar: sidebar 
keywords: upgrade paths, scv, 6.1 
summary: Informieren Sie sich über die neuen Funktionen des SnapCenter Plug-in for VMware vSphere 6.1. 
---
= Upgrade-Pfade
:allow-uri-read: 


[role="lead"]
Auf welche Version des SnapCenter Plug-in for VMware vSphere (SCV) Sie aktualisieren können, hängt von der Version ab, die Sie derzeit ausführen.

[NOTE]
====
Das Upgrade auf das SnapCenter Plug-in for VMware vSphere (SCV) 4.8 und höher wird nur auf VMware vCenter Server 7 Update 1 und späteren Versionen unterstützt.  Für VMware vCenter-Server vor Version 7 Update 1 sollten Sie weiterhin SCV 4.7 verwenden.

====
[cols="50%,50%"]
|===
| Wenn Sie die SCV-Version verwenden … | Sie können SCV direkt aktualisieren auf … 


 a| 
SCV 6,0
 a| 
SCV 6,1



 a| 
SCV 5,0
 a| 
SCV 6.0 und SCV 6.1



 a| 
SCV 4,9
 a| 
SCV 5.0 und SCV 6.0



 a| 
SCV 4,8
 a| 
SCV 4.9 und SCV 5.0



 a| 
SCV 4,7
 a| 
SCV 4.8 und SCV 4.9

|===
Für virtualisierte Datenbanken und Dateisysteme, die in SnapCenter integriert sind, ist dies der Upgradepfad:

[cols="30%,30%,40%"]
|===
| Wenn Sie | Wenn Ihr VMware-Plug-In … ist | Sie können direkt upgraden auf… 


 a| 
SnapCenter 6.1
 a| 
SCV 6,0
 a| 
SCV 6,1



 a| 
SnapCenter 6.0
 a| 
SCV 5,0
 a| 
SCV 6,0



 a| 
SnapCenter 5.0
 a| 
SCV 4,9
 a| 
SCV 5,0



 a| 
SnapCenter 4.9
 a| 
SCV 4,8
 a| 
SCV 4,9



 a| 
SnapCenter 4.8
 a| 
SCV 4,7
 a| 
SCV 4,8

|===
Aktuelle Informationen zu unterstützten Versionen finden Sie unter https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["NetApp Interoperabilitätsmatrix-Tool"^] (IMT).
